version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (python): "
    groups: 
      pip:
        applies-to: version-updates
        patterns:
          - "*"
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message: 
      prefix: "Dependabot (github actions): "
    groups: 
      gh-actions:
        applies-to: version-updates
        patterns:
          - "*"
      gh-actions-security:
        applies-to: security-updates
        patterns:
          - "*"