name: Splunk packager
description: Run splunk app packager
inputs:
  app_package_path:
    description: The Splunk app package path.
    required: true
    type: string
  splunk_username:
    description: The splunk username.
    required: true
    type: string
  splunk_password:
    description: The splunk password.
    required: true
    type: string
  splunk_acs_token:
    description: The splunk acs token.
    required: true
    type: string
  splunk_acs_stack:
    description: The splunk stack.
    required: true
    type: string
  config_toml_path:
    description: Path to your config.toml file.
    required: true
    type: string
    default: config.toml
  production:
    description: Boolean stating you would like to push to production
    required: false
    type: boolean
    default: true
runs:
  using: composite
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
        architecture: 'x64'
        cache: 'pip'

    - name: Install splunk-app-packager
      shell: bash
      run: pip install splunk-app-packager==0.0.3

    - name: package, validate, deploy (production)
      shell: bash
      env:
        SPLUNK_USER: ${{ inputs.splunk_username }}
        SPLUNK_PASSWORD: ${{ inputs.splunk_password }}
        SPLUNK_ACS_TOKEN: ${{ inputs.splunk_acs_token }}
        SPLUNK_ACS_STACK: ${{ inputs.splunk_acs_stack }}
      run: sap --prod ${{ inputs.app_package_path }} --config-path ${{ inputs.config_toml_path }}
      if: ${{ inputs.production == true }}


    - name: package, validate, deploy (development)
      shell: bash
      env:
        SPLUNK_USER: ${{ inputs.splunk_username }}
        SPLUNK_PASSWORD: ${{ inputs.splunk_password }}
        SPLUNK_ACS_TOKEN: ${{ inputs.splunk_acs_token }}
        SPLUNK_ACS_STACK: ${{ inputs.splunk_acs_stack }}
      run: sap ${{ inputs.app_package_path }} --config-path ${{ inputs.config_toml_path }}
      if: ${{ inputs.production == false }}
    
