name: Splunk packager
description: Run splunk app packager
inputs:
  app_package_path:
    description: The Splunk app package path.
    required: true
    type: string
  splunk_username:
    description: The splunk username.
    required: true
    type: string
  splunk_password:
    description: The splunk password.
    required: true
    type: string
  splunk_acs_token:
    description: The splunk acs token.
    required: true
    type: string
  splunk_acs_stack:
    description: The splunk stack.
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
        architecture: 'x64'
        cache: 'pip'
    
    - run: pip install -U setuptools && pip install -r requirements.txt
      shell: bash

    - name: Pip audit
      shell: bash
      run: pip-audit -S

    - name: package, validate, deploy
      shell: bash
      env:
        SPLUNK_USER: ${{ inputs.splunk_username }}
        SPLUNK_PASSWORD: ${{ inputs.splunk_password }}
        SPLUNK_ACS_TOKEN: ${{ inputs.splunk_acs_token }}
        SPLUNK_ACS_STACK: ${{ inputs.splunk_acs_stack }}
      run: src/splunk_app_packager/package.py --prod DCAP
